language: java
install:
   - cp gradle.properties0 gradle.properties
   - ./gradlew assemble
test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)
